--AlTER TABLE DE FIDE_CATEGORIAS_TB
ALTER TABLE FIDE_CATEGORIAS_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_CATEGORIAS_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_CATEGORIAS_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_CATEGORIAS_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_CATEGORIAS_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_RESENAS_PRODUCTO_TB
ALTER TABLE FIDE_RESENAS_PRODUCTO_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_RESENAS_PRODUCTO_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_RESENAS_PRODUCTO_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_RESENAS_PRODUCTO_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_RESENAS_PRODUCTO_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_PRODUCTOS_TB
ALTER TABLE FIDE_PRODUCTOS_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_PRODUCTOS_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_PRODUCTOS_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_PRODUCTOS_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_PRODUCTOS_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_CLIENTES_TB
ALTER TABLE FIDE_CLIENTES_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_CLIENTES_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_CLIENTES_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_CLIENTES_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_CLIENTES_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_EMPLEADOS_TB
ALTER TABLE FIDE_EMPLEADOS_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_EMPLEADOS_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_EMPLEADOS_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_EMPLEADOS_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_EMPLEADOS_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_PROVEEDORES_TB
ALTER TABLE FIDE_PROVEEDORES_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_PROVEEDORES_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_PROVEEDORES_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_PROVEEDORES_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_PROVEEDORES_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_CARRITO_TB
ALTER TABLE FIDE_CARRITO_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_CARRITO_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_CARRITO_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_CARRITO_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_CARRITO_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_VENTA_TB
ALTER TABLE FIDE_VENTA_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_VENTA_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_VENTA_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_VENTA_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_VENTA_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_DETALLE_VENTA_TB
ALTER TABLE FIDE_DETALLE_VENTA_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_DETALLE_VENTA_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_DETALLE_VENTA_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_DETALLE_VENTA_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_DETALLE_VENTA_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_RECLAMACIONES_TB
ALTER TABLE FIDE_RECLAMACIONES_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_RECLAMACIONES_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_RECLAMACIONES_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_RECLAMACIONES_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_RECLAMACIONES_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_DESCRIPCION_TB
ALTER TABLE FIDE_DESCRIPCION_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_DESCRIPCION_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_DESCRIPCION_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_DESCRIPCION_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_DESCRIPCION_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_MOTIVOS_TB
ALTER TABLE FIDE_MOTIVOS_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_MOTIVOS_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_MOTIVOS_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_MOTIVOS_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_MOTIVOS_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_COMPRAS_TB
ALTER TABLE FIDE_COMPRAS_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_COMPRAS_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_COMPRAS_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_COMPRAS_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_COMPRAS_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_ORDEN_DEL_DIA_TB
ALTER TABLE FIDE_ORDEN_DEL_DIA_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_ORDEN_DEL_DIA_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_ORDEN_DEL_DIA_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_ORDEN_DEL_DIA_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_ORDEN_DEL_DIA_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_REABASTECIMIENTO_STOCK_TB
ALTER TABLE FIDE_REABASTECIMIENTO_STOCK_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_REABASTECIMIENTO_STOCK_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_REABASTECIMIENTO_STOCK_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_REABASTECIMIENTO_STOCK_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_REABASTECIMIENTO_STOCK_TB
ADD V_ACCION VARCHAR2(100);

--AlTER TABLE DE FIDE_PRMOCIONES_TB
ALTER TABLE FIDE_PROMOCIONES_TB
ADD V_CREATED_BY VARCHAR2(100);

ALTER TABLE FIDE_PROMOCIONES_TB
ADD V_CREATION_DATE DATE;

ALTER TABLE FIDE_PROMOCIONES_TB
ADD V_LAST_UPDATE_BY VARCHAR2(100);

ALTER TABLE FIDE_PROMOCIONES_TB
ADD V_LAST_UPDATE_DATE DATE;

ALTER TABLE FIDE_PROMOCIONES_TB
ADD V_ACCION VARCHAR2(100);
