--Cursores
--CREADO POR MARIA Celeste SOLANO HIDALGO
--FECHA 25/07/2024
--Función #1
--Procedimiento para seleccionar todos los estados
CREATE OR REPLACE PROCEDURE SELECCIONAR_ESTADOS_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_ESTADOS_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_ESTADOS_SP(:MY_CURSOR);
PRINT MY_CURSOR;

 --CREADO POR MARIA Celeste SOLANO HIDALGO
--FECHA 25/07/2024
--Función #2
--Procedimiento para seleccionar todos los estados
-- Procedimiento para seleccionar todas las categorías
CREATE OR REPLACE PROCEDURE SELECCIONAR_CATEGORIAS_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_CATEGORIAS_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_CATEGORIAS_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR MARIA Celeste SOLANO HIDALGO
--FECHA 25/07/2024
--Función #3
--Procedimiento para seleccionar todos los estados
--Procedimiento para seleccionar todos los productos
CREATE OR REPLACE PROCEDURE SELECCIONAR_PRODUCTOS_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_PRODUCTOS_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_PRODUCTOS_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR MARIA Celeste SOLANO HIDALGO
--FECHA 25/07/2024
--Función #4
--Procedimiento para seleccionar todos los estados
-- Procedimiento para seleccionar todos los clientes
CREATE OR REPLACE PROCEDURE SELECCIONAR_CLIENTES_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_CLIENTES_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_CLIENTES_SP(:MY_CURSOR);
PRINT MY_CURSOR;

--CREADO POR Marcos Solis
--FECHA 25/07/2024
--Función #5
-- Procedimiento para seleccionar todos los empleados
CREATE OR REPLACE PROCEDURE SELECCIONAR_EMPLEADOS_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_EMPLEADOS_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_EMPLEADOS_SP(:MY_CURSOR);
PRINT MY_CURSOR;

--CREADO POR Marcos Solis
--FECHA 25/07/2024
--Función #6
-- Procedimiento para seleccionar todos los proveedores
CREATE OR REPLACE PROCEDURE SELECCIONAR_PROVEEDORES_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_PROVEEDORES_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_PROVEEDORES_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Marcos Solis
--FECHA 25/07/2024
--Función #7
-- Procedimiento para seleccionar todos los carritos
CREATE OR REPLACE PROCEDURE SELECCIONAR_CARRITO_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_CARRITO_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_CARRITO_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Anderson Ulate
--FECHA 25/07/2024
--Función #8
-- Procedimiento para seleccionar todas las ventas
CREATE OR REPLACE PROCEDURE SELECCIONAR_VENTA_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_VENTA_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_VENTA_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Anderson Ulate
--FECHA 25/07/2024
--Función #9
-- Procedimiento para seleccionar todos los detalles de venta
CREATE OR REPLACE PROCEDURE SELECCIONAR_DETALLE_VENTA_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_DETALLE_VENTA_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_DETALLE_VENTA_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Anderson Ulate
--FECHA 25/07/2024
--Función #10
-- Procedimiento para seleccionar todas las reclamaciones
CREATE OR REPLACE PROCEDURE SELECCIONAR_RECLAMACIONES_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_RECLAMACIONES_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_RECLAMACIONES_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Anderson Ulate
--FECHA 25/07/2024
--Función #11
-- Procedimiento para seleccionar todas las descripciones
CREATE OR REPLACE PROCEDURE SELECCIONAR_DESCRIPCIONES_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_DESCRIPCION_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_DESCRIPCIONES_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Anderson Ulate
--FECHA 25/07/2024
--Función #12
-- Procedimiento para seleccionar todos los motivos
CREATE OR REPLACE PROCEDURE SELECCIONAR_MOTIVOS_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_MOTIVOS_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_MOTIVOS_SP(:MY_CURSOR);
PRINT MY_CURSOR;

--CREADO POR Anderson Ulate
--FECHA 25/07/2024
--Función #13 
-- Procedimiento para seleccionar todas las promociones
CREATE OR REPLACE PROCEDURE SELECCIONAR_PROMOCIONES_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_PROMOCIONES_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_PROMOCIONES_SP(:MY_CURSOR);
PRINT MY_CURSOR;

--CREADO POR Nicole Hidalgo
--FECHA 25/07/2024
--Función #14 
-- Procedimiento para seleccionar todas las reseñas de productos
CREATE OR REPLACE PROCEDURE SELECCIONAR_RESENAS_PRODUCTO_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_RESENAS_PRODUCTO_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_RESENAS_PRODUCTO_SP(:MY_CURSOR);
PRINT MY_CURSOR;

--CREADO POR Nicole Hidalgo
--FECHA 25/07/2024
--Función #15
-- Procedimiento para seleccionar todas las compras
CREATE OR REPLACE PROCEDURE SELECCIONAR_COMPRAS_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_COMPRAS_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_COMPRAS_SP(:MY_CURSOR);
PRINT MY_CURSOR;

 
--CREADO POR Nicole Hidalgo
--FECHA 25/07/2024
--Función #16
-- Procedimiento para seleccionar todas las órdenes del día
CREATE OR REPLACE PROCEDURE SELECCIONAR_ORDEN_DEL_DIA_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_ORDEN_DEL_DIA_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_ORDEN_DEL_DIA_SP(:MY_CURSOR);
PRINT MY_CURSOR;
 
--CREADO POR Nicole Hidalgo
--FECHA 25/07/2024
--Función #17
-- Procedimiento para seleccionar todos los reabastecimientos de stock
CREATE OR REPLACE PROCEDURE SELECCIONAR_REABASTECIMIENTO_STOCK_SP(
  p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN p_cursor FOR SELECT * FROM FIDE_REABASTECIMIENTO_STOCK_TB;
END;

VAR MY_CURSOR REFCURSOR;
EXEC SELECCIONAR_REABASTECIMIENTO_STOCK_SP(:MY_CURSOR);
PRINT MY_CURSOR;